package probe

import (
	"context"
	"os"
	"os/exec"
	"testing"
)

// TestLiveProbe runs the full Probe path against a real synthetic media file
// generated by ffmpeg. Skipped when ffmpeg/ffprobe are unavailable.
func TestLiveProbe(t *testing.T) {
	if _, err := exec.LookPath("ffprobe"); err != nil {
		t.Skip("ffprobe not available")
	}
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not available")
	}

	tmp := t.TempDir()
	path := tmp + "/test.mp4"

	// Generate a 1-second H264+AAC file.
	gen := exec.Command("ffmpeg",
		"-f", "lavfi", "-i", "testsrc=duration=1:size=1280x720:rate=24",
		"-f", "lavfi", "-i", "sine=frequency=440:duration=1:sample_rate=48000",
		"-c:v", "libx264", "-profile:v", "high", "-pix_fmt", "yuv420p",
		"-c:a", "aac", "-ac", "2",
		"-y", path,
	)
	gen.Stderr = os.Stderr
	if err := gen.Run(); err != nil {
		t.Fatalf("ffmpeg generate: %v", err)
	}

	pr, err := Probe(context.Background(), path)
	if err != nil {
		t.Fatalf("Probe: %v", err)
	}

	t.Logf("Format:     %s (%s)", pr.Format.FormatName, pr.Format.Filename)
	t.Logf("Streams:    %d", pr.Format.NbStreams)
	t.Logf("Duration:   %.3f s", pr.Format.Duration)
	t.Logf("Size:       %d bytes", pr.Format.Size)
	t.Logf("FmtBitRate: %d bps", pr.Format.BitRate)

	// Validate primary video.
	if pr.PrimaryVideo == nil {
		t.Fatal("PrimaryVideo is nil")
	}
	v := pr.PrimaryVideo
	t.Logf("Video[%d]:   %s (profile=%s, pix=%s)", v.Index, v.Codec, v.Profile, v.PixFmt)
	t.Logf("Resolution: %s", pr.Resolution())
	t.Logf("BitRate:    stream=%d effective=%d", v.BitRate, pr.VideoBitRate())
	t.Logf("FieldOrder: %s", v.FieldOrder)
	t.Logf("HDR:        %s", pr.HDRType())
	t.Logf("Interlaced: %v", pr.IsInterlaced())
	t.Logf("EdgeSafe:   %v", pr.IsEdgeSafeHEVC())

	if v.Codec != "h264" {
		t.Errorf("expected h264, got %q", v.Codec)
	}
	if pr.Resolution() != "1280x720" {
		t.Errorf("expected 1280x720, got %s", pr.Resolution())
	}
	if pr.HDRType() != "sdr" {
		t.Errorf("expected sdr, got %s", pr.HDRType())
	}
	if pr.IsInterlaced() {
		t.Error("synthetic file should not be interlaced")
	}

	// Audio validation.
	if len(pr.AudioStreams) != 1 {
		t.Fatalf("expected 1 audio stream, got %d", len(pr.AudioStreams))
	}
	a := pr.AudioStreams[0]
	t.Logf("Audio[0]:   %s, %dch, sr=%d, default=%v", a.Codec, a.Channels, a.SampleRate, a.IsDefault)
	if a.Codec != "aac" {
		t.Errorf("expected aac, got %q", a.Codec)
	}
	if a.Channels != 2 {
		t.Errorf("expected 2 channels, got %d", a.Channels)
	}

	// No subtitles in synthetic file.
	if len(pr.SubtitleStreams) != 0 {
		t.Errorf("expected 0 subtitle streams, got %d", len(pr.SubtitleStreams))
	}

	t.Log("--- LIVE PROBE OK ---")
}
